# Generated by Django 4.2.3 on 2023-07-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Querys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=300)),
            ],
        ),
    ]
